name: Master Branch

on:
  pull_request:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.6

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.x

      - name: Install Golang Modules
        run: go mod tidy
        working-directory: ./terratest

      - name: Test Terraform Code
        run: go test s3_test.go
        working-directory: ./terratest
